#!/usr/bin/env python3
"""Check today's and yesterday's top GitHub repositories."""

import requests
from datetime import datetime, timedelta

GITHUB_API = "https://api.github.com/search/repositories"
HEADERS = {"Accept": "application/vnd.github.v3+json", "User-Agent": "MistralVibe/1.0"}

def get_top_repos(query, sort_by="stars", per_page=30):
    params = {"q": query, "sort": sort_by, "order": "desc", "per_page": per_page}
    try:
        response = requests.get(GITHUB_API, headers=HEADERS, params=params, timeout=30)
        response.raise_for_status()
        return response.json().get("items", [])
    except Exception as e:
        return []

def display_repos(repos, title, max_display=10):
    if not repos:
        print(f"\n{title}: No repositories found")
        return
    print(f"\n{'='*80}")
    print(f"{title}")
    print(f"{'='*80}")
    print(f"{'#':<4} {'Repository':<35} {'Stars':<10} {'Forks':<10} {'Lang':<8}")
    print(f"{'-'*80}")
    for i, repo in enumerate(repos[:max_display], 1):
        name = repo["full_name"]
        stars = repo["stargazers_count"]
        forks = repo["forks_count"]
        language = repo["language"] or "N/A"
        print(f"{i:<4} {name:<35} {stars:<10} {forks:<10} {language:<8}")
    if len(repos) > max_display:
        print(f"\n... and {len(repos) - max_display} more")
    print()

def main():
    print("\n" + "="*80)
    print("GITHUB REPOSITORY INTELLIGENCE - DAILY REPORT")
    print("Generated by: Mistral Vibe | Capability: Repository Intelligence")
    print(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*80)
    
    today = datetime.now()
    yesterday = today - timedelta(days=1)
    week_ago = today - timedelta(days=7)
    month_ago = today - timedelta(days=30)
    
    today_str = today.strftime("%Y-%m-%d")
    yesterday_str = yesterday.strftime("%Y-%m-%d")
    week_ago_str = week_ago.strftime("%Y-%m-%d")
    month_ago_str = month_ago.strftime("%Y-%m-%d")
    
    print(f"\n📅 Analysis Period: {month_ago_str} to {today_str}")
    
    today_repos = get_top_repos(f"created:>{today_str}", sort_by="stars", per_page=20)
    display_repos(today_repos, f"🔥 Created Today (Top by Stars)", max_display=10)
    
    today_updated = get_top_repos(f"pushed:>{today_str}", sort_by="stars", per_page=20)
    display_repos(today_updated, f"🔄 Updated Today (Top by Stars)", max_display=10)
    
    yesterday_repos = get_top_repos(f"created:{yesterday_str}", sort_by="stars", per_page=20)
    display_repos(yesterday_repos, f"📅 Created Yesterday (Top by Stars)", max_display=10)
    
    week_repos = get_top_repos(f"created:>{week_ago_str}", sort_by="stars", per_page=30)
    display_repos(week_repos, f"📈 This Week's Trending (Top by Stars)", max_display=15)
    
    fast_growing = get_top_repos(f"created:>{week_ago_str} stars:>100", sort_by="stars", per_page=20)
    display_repos(fast_growing, f"🚀 Fastest Growing (100+ stars, this week)", max_display=10)
    
    most_forked = get_top_repos(f"created:>{week_ago_str}", sort_by="forks", per_page=20)
    display_repos(most_forked, f"🍴 Most Forked This Week", max_display=10)
    
    print("="*80)
    print("✅ Repository Intelligence Analysis Complete!")
    print("="*80 + "\n")

if __name__ == "__main__":
    main()
